name:                alpine-haskell
version:             0.1.0.0
homepage:            https://github.com/githubuser/alpine-haskell#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

flags:
  static:
    description: Statically link executables.
    manual: true
    default: false

executables:
  demo:
    source-dirs:      executables
    main:             Main.hs
    when:
      - condition: flag(static)
        then:
          ld-options: -static
          ghc-options: "-rtsopts -threaded -optc-Os -optl=-pthread -optl=-static -fPIC"
        else:
          ghc-options: "-rtsopts -threaded"
